sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
branches:
  only:
    - master
    - develop
    - "/v\\d+\\.\\d+\\.\\d+(-\\w+)?/"
stages:
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: lint
      script:
        - npm link
        - npm run lint
        - npm run compile
    - stage: test
      script:
        - npm link
        - npm run test:coverage
        - npm run coveralls
    - stage: deploy
      if: tag IS present
      script:
        - npm link
        - npx truffle migrate --network infura_rinkeby
        - npx ghu issue -k "$GITHUB_API_TOKEN" -o pandoraboxchain -r pyrrha-webclient,pyrrha-pynode,pyrrha-boxproxy,pyrrha -t "Contracts addresses update required" -b "Pandora:$(< ./build/addresses/Pandora.json), PandoraMarket:$(< ./build/addresses/PandoraMarket.json)"
