sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
branches:
  only:
    - master
    - "/v\\d+\\.\\d+\\.\\d+(-\\w+)?/"
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      install: skip
      script:
      - echo "Tests are skiped for now"
    - stage: build
      if: tag IS present
      script:
        - npm link
        - npx truffle migrate --network infura_rinkeby
        - npx ghu issue -k "$GITHUB_API_TOKEN" -o pandoraboxchain -r pyrrha-webclient,pyrrha-pynode,pyrrha-boxproxy,pyrrha -t "Contracts addresses update required" -b "Pandora:$(< ./build/addresses/Pandora.json), PandoraMarket:$(< ./build/addresses/PandoraMarket.json)"
