sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
branches:
  only:
    - enable-travis-ci
    - "/v\\d+\\.\\d+\\.\\d+(-\\w+)?/"
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      script:
      - echo "Tests are skiped for now"
    - stage: build
      if: tag IS present
      script:
        - npx truffle migrate --network infura_rinkeby
        - npx ghu issue -k "$GITHUB_API_TOKEN" -o pandoraboxchain -r github-utils -t "Contracts addresses update required" -b "Pandora: $(< ./build/addresses/Pandora.json),\nPandoraMarket: $(< ./build/addresses/PandoraMarket.json)"
